export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCTS_LIST_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const PRODUCTS_LIST_FAILURE = "GET_PRODUCTS_FAILURE";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_INPUT_CHANGE = "ADD_INPUT_CHANGE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_INPUT_CHANGES = "EDIT_INPUT_CHANGES";
export const EDIT_SUCCESS_PRODUCT = "EDIT_SUCCESS_PRODUCT";
export const PAGINATE = "PAGINATE";
export const MODAL_TOGGLE = "MODAL_TOGGLE";

